# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Array-Basics" data-toc-modified-id="Array-Basics-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Array Basics</a></div><div class="lev2 toc-item"><a href="#Shape-and-Dimension" data-toc-modified-id="Shape-and-Dimension-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Shape and Dimension</a></div><div class="lev3 toc-item"><a href="#Create-Two-Dimensional-Array" data-toc-modified-id="Create-Two-Dimensional-Array-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Create Two-Dimensional Array</a></div><div class="lev3 toc-item"><a href="#Changing-Dimensions" data-toc-modified-id="Changing-Dimensions-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Changing Dimensions</a></div><div class="lev3 toc-item"><a href="#Flat-Arrays" data-toc-modified-id="Flat-Arrays-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Flat Arrays</a></div><div class="lev2 toc-item"><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Creating Arrays</a></div><div class="lev3 toc-item"><a href="#Functions-that-Return-Arrays" data-toc-modified-id="Functions-that-Return-Arrays-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Functions that Return Arrays</a></div><div class="lev3 toc-item"><a href="#Manual-Array-Definitions" data-toc-modified-id="Manual-Array-Definitions-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Manual Array Definitions</a></div><div class="lev2 toc-item"><a href="#Array-Indexing" data-toc-modified-id="Array-Indexing-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Array Indexing</a></div><div class="lev2 toc-item"><a href="#Passing-Arrays" data-toc-modified-id="Passing-Arrays-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Passing Arrays</a></div><div class="lev1 toc-item"><a href="#Operations-on-Arrays" data-toc-modified-id="Operations-on-Arrays-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Operations on Arrays</a></div><div class="lev2 toc-item"><a href="#Matrix-Algebra" data-toc-modified-id="Matrix-Algebra-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Matrix Algebra</a></div><div class="lev2 toc-item"><a href="#Elementwise-Operations" data-toc-modified-id="Elementwise-Operations-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Elementwise Operations</a></div><div class="lev3 toc-item"><a href="#Algebraic-Operations" data-toc-modified-id="Algebraic-Operations-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Algebraic Operations</a></div><div class="lev3 toc-item"><a href="#Elementwise-Comparisons" data-toc-modified-id="Elementwise-Comparisons-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Elementwise Comparisons</a></div><div class="lev3 toc-item"><a href="#Vectorized-Functions" data-toc-modified-id="Vectorized-Functions-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Vectorized Functions</a></div><div class="lev1 toc-item"><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Linear Algebra</a></div>

# Array Basics

## Shape and Dimension

In [69]:
a = [10, 20, 30]

3-element Array{Int64,1}:
 10
 20
 30

In [70]:
size(a)

(3,)

In [71]:
ndims(a)

1

### Create Two-Dimensional Array

In [72]:
eye(3)

3x3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [73]:
diagm([2, 4])

2x2 Array{Int64,2}:
 2  0
 0  4

In [74]:
diagm([1,2,3,4])

4x4 Array{Int64,2}:
 1  0  0  0
 0  2  0  0
 0  0  3  0
 0  0  0  4

### Changing Dimensions

In [75]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [76]:
b = reshape(a, 2, 2)

2x2 Array{Int64,2}:
 10  30
 20  40

In [77]:
b[1, 1]

10

In [78]:
b[1, 1] = 100

100

In [79]:
a  # First element has changed

4-element Array{Int64,1}:
 100
  20
  30
  40

In [80]:
# To collapse an array along one dimension you can use squeeze()
a = [1 2 3 4]  # Two dimensional
squeeze(a, 1)

4-element Array{Int64,1}:
 1
 2
 3
 4

### Flat Arrays

As we’ve seen, in Julia we have both
* one-dimensional arrays (i.e., flat arrays)
* arrays of size (1, n) or (n, 1) that represent row and column vectors respectively

## Creating Arrays

### Functions that Return Arrays

In [81]:
eye(2)

2x2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [82]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [83]:
# Empty Array
Array(Float64, 2, 2) # The printed values you see here are just garbage values

2x2 Array{Float64,2}:
 6.48937e-314  2.23711e-314
 2.23705e-314  2.28093e-314

In [84]:
ones(2, 2)

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [85]:
fill("foo", 2, 2)

2x2 Array{ASCIIString,2}:
 "foo"  "foo"
 "foo"  "foo"

### Manual Array Definitions

In [86]:
a = [10, 20, 30, 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [87]:
ndims(a)

1

In [88]:
a = [10 20 30 40]  # Two dimensional, shape is 1 x n

1x4 Array{Int64,2}:
 10  20  30  40

In [89]:
ndims(a)

2

In [90]:
a = [10 20; 30 40]  # 2 x 2

2x2 Array{Int64,2}:
 10  20
 30  40

In [91]:
a = [10; 20; 30; 40]

4-element Array{Int64,1}:
 10
 20
 30
 40

In [92]:
a = [10 20 30 40]' # Transpose

4x1 Array{Int64,2}:
 10
 20
 30
 40

## Array Indexing

In [93]:
a = collect(2a[end-1]0:10:40)

LoadError: LoadError: syntax: missing comma or ) in argument list
while loading In[93], in expression starting on line 1

In [94]:
a = collect(10:10:40)

4-element Array{Int64,1}:
 10
 20
 30
 40

In [95]:
a[end-1]

30

In [96]:
a[1:3]

3-element Array{Int64,1}:
 10
 20
 30

In [97]:
a = randn(2, 2)

2x2 Array{Float64,2}:
 -2.14103   -1.09509 
 -0.568367   0.429548

In [98]:
a[1, 1]

-2.141033471226224

In [99]:
a[1, :]  # First row

1x2 Array{Float64,2}:
 -2.14103  -1.09509

In [100]:
a[:, 1]  # First column

2-element Array{Float64,1}:
 -2.14103 
 -0.568367

Booleans can be used to extract elements

In [101]:
a = randn(2, 2)

2x2 Array{Float64,2}:
 -1.58487   -0.14634 
 -0.840351  -0.636154

In [102]:
b = [true false; false true]

2x2 Array{Bool,2}:
  true  false
 false   true

In [103]:
a[b]

2-element Array{Float64,1}:
 -1.58487 
 -0.636154

In [104]:
a = Array(Float64, 4)
a[2:end] = 42
a

4-element Array{Float64,1}:
  6.60301e-314
 42.0         
 42.0         
 42.0         

## Passing Arrays

In [105]:
a = ones(3)
b  = a
b[3]  = 10
a

3-element Array{Float64,1}:
  1.0
  1.0
 10.0

In [106]:
a = ones(3)
b  = copy(a)
b[3]  = 10
a

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

# Operations on Arrays

In [107]:
a = [-1, 0, 1]

3-element Array{Int64,1}:
 -1
  0
  1

In [108]:
b = sort(a, rev=true)

3-element Array{Int64,1}:
  1
  0
 -1

In [109]:
b === a  # === tests if arrays are identical (i.e share same memory)

false

## Matrix Algebra

`*` means matrix multiplication

In [110]:
# To solve the linear system A X = B for X use A \ B
A = [1 2; 2 3]
B = ones(2, 2)
A \ B

2x2 Array{Float64,2}:
 -1.0  -1.0
  1.0   1.0

## Elementwise Operations

### Algebraic Operations

In [111]:
ones(2, 2) * ones(2, 2)   # Matrix multiplication

2x2 Array{Float64,2}:
 2.0  2.0
 2.0  2.0

In [112]:
ones(2, 2) .* ones(2, 2)   # Element by element multiplication

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [113]:
# .x means apply operator x elementwise
A = -ones(2, 2)
A.^2 

2x2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

### Elementwise Comparisons

In [114]:
a = [10, 20, 30]
b = [-100, 0, 100]

3-element Array{Int64,1}:
 -100
    0
  100

In [115]:
b .> a

3-element BitArray{1}:
 false
 false
  true

In [116]:
 b .> 0

3-element BitArray{1}:
 false
 false
  true

In [117]:
a[a .< 20]

1-element Array{Int64,1}:
 10

### Vectorized Functions

Functions that act elementwise on arrays in this manner are called vectorized functions

# Linear Algebra

In [118]:
A = [1 2; 3 4]

2x2 Array{Int64,2}:
 1  2
 3  4

In [119]:
det(A)

-2.0

In [120]:
trace(A)

5

In [121]:
eigvals(A)

2-element Array{Float64,1}:
 -0.372281
  5.37228 

In [122]:
rank(A)

2